apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-classifier-fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iris-classifier-fastapi
  template:
    metadata:
      labels:
        app: iris-classifier-fastapi
    spec:
      containers:
      - name: iris-classifier-fastapi
        image: us-central1-docker.pkg.dev/clean-vista-473214-i6/iris-classifier-docker/iris-classifier-fastapi:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: iris-classifier-fastapi-service
spec:
  type: LoadBalancer
  selector:
    app: iris-classifier-fastapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
